### ISSUE TITLE
error can't use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by bounmed** [f6p/torrent-ratio-faker#3]
```

self.allContentReceived()
  File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 866, in requestReceived
    self.process()
  File "./trf", line 17, in process
    self.__multiply('downloaded', FakerProxyRequest.download)
  File "./trf", line 23, in __multiply
    match = re.search(regex, self.uri)
  File "/usr/lib/python3.4/re.py", line 166, in search
    return _compile(pattern, flags).search(string)
builtins.TypeError: can't use a string pattern on a bytes-like object
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 2125, in dataReceived
    return basic.LineReceiver.dataReceived(self, data)
  File "/usr/local/lib/python3.4/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 2013, in lineReceived
    self.allContentReceived()
  File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.4/dist-packages/twisted/web/http.py", line 866, in requestReceived
    self.process()
  File "./trf", line 17, in process
    self.__multiply('downloaded', FakerProxyRequest.download)
  File "./trf", line 23, in __multiply
    match = re.search(regex, self.uri)
  File "/usr/lib/python3.4/re.py", line 166, in search
    return _compile(pattern, flags).search(string)
builtins.TypeError: can't use a string pattern on a bytes-like object
```

**Comment by f6p** [comment]
Thx for the report.

I ported it from Python2 to Python3 so it should be usable again.

Cheers
🍷
