### ISSUE TITLE
It seems that your script is currently incompatible with the latest twisted library. Can you update it?

### ISSUE THREAD

**Issue by zhbrcn** [f6p/torrent-ratio-faker#4]
Unhandled Error
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/twisted/python/log.py", line 96, in callWithLogger
return callWithContext({"system": lp}, func, *args, **kw)
File "/usr/local/lib/python3.9/dist-packages/twisted/python/log.py", line 80, in callWithContext
return context.call({ILogContext: newCtx}, func, *args, **kw)
File "/usr/local/lib/python3.9/dist-packages/twisted/python/context.py", line 117, in callWithContext
return self.currentContext().callWithContext(ctx, func, *args, **kw)
File "/usr/local/lib/python3.9/dist-packages/twisted/python/context.py", line 82, in callWithContext
return func(*args, **kw)
--- <exception caught here> ---
File "/usr/local/lib/python3.9/dist-packages/twisted/internet/posixbase.py", line 487, in _doReadOrWrite
why = selectable.doRead()
File "/usr/local/lib/python3.9/dist-packages/twisted/internet/tcp.py", line 248, in doRead
return self._dataReceived(data)
File "/usr/local/lib/python3.9/dist-packages/twisted/internet/tcp.py", line 253, in _dataReceived
rval = self.protocol.dataReceived(data)
File "/usr/local/lib/python3.9/dist-packages/twisted/web/http.py", line 2465, in dataReceived
return basic.LineReceiver.dataReceived(self, data)
File "/usr/local/lib/python3.9/dist-packages/twisted/protocols/basic.py", line 549, in dataReceived
why = self.lineReceived(line)
File "/usr/local/lib/python3.9/dist-packages/twisted/web/http.py", line 2319, in lineReceived
self.allContentReceived()
File "/usr/local/lib/python3.9/dist-packages/twisted/web/http.py", line 2447, in allContentReceived
req.requestReceived(command, path, version)
File "/usr/local/lib/python3.9/dist-packages/twisted/web/http.py", line 1032, in requestReceived
self.process()
File "/root/torrent-ratio-faker/bin/trf", line 19, in process
proxy.ProxyRequest.process(self)
File "/usr/local/lib/python3.9/dist-packages/twisted/web/proxy.py", line 137, in process
port = self.ports[protocol]
builtins.KeyError: b''

**Comment by f6p** [comment]
It works for me with python 3.11.2 and twisted 22.10.0.

**Comment by zhbrcn** [comment]
Hello:
I tried python 3.11.2 and twisted 22.10.0, and it still shows the same error.
I am using qBittorrent under Debian, does it only fit Azureus?

**Comment by f6p** [comment]
qBittorent's proxy support was dysfunctional for a long time. I would try different client.
